# Generated by GPT-5.2 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_variantstyle"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantGender",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]

