# Generated by GPT-5.2 on 2026-04-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_variantgender"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.variantgender",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reseller_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]

