# Generated by Django 5.2.13 on 2026-05-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_variantcolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantColor',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'reseller_price')},
        ),
    ]
