# Generated by Django 5.2.13 on 2026-04-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.RemoveField(
            model_name='inventorymove',
            name='po_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tailoringjob',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='poitem',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='tailoringjob',
            name='tailor',
        ),
        migrations.DeleteModel(
            name='InventoryMove',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='POItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Tailor',
        ),
        migrations.DeleteModel(
            name='TailoringJob',
        ),
    ]
