# Generated by Django 5.2.13 on 2026-04-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(choices=[('store', 'Store'), ('website', 'Website')], max_length=10)),
                ('to_location', models.CharField(choices=[('store', 'Store'), ('website', 'Website')], max_length=10)),
                ('qty', models.PositiveIntegerField()),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='vendors.poitem')),
            ],
        ),
    ]
