# Generated by Django 5.2.13 on 2026-04-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('vendors', '0002_remove_poitem_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymove',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='vendors.purchaseorderitem'),
        ),
    ]
