# Generated by Django 5.2.13 on 2026-05-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorymove_po_item'),
        ('products', '0007_alter_product_image'),
        ('vendors', '0016_purchaseorderitem_defective_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymove',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventorymove',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='vendors.purchaseorderitem'),
        ),
    ]
