# Generated by Django 5.2.13 on 2026-04-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TailoringJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50, unique=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Done', 'Done'), ('Delivered', 'Delivered')], default='Assigned', max_length=20)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('expected_time', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailoring_jobs', to='orders.orderitem')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='tailoring.tailor')),
            ],
        ),
    ]
