# Generated by Django 5.2.13 on 2026-04-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorymove_po_item'),
        ('vendors', '0002_remove_poitem_purchase_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POItem',
        ),
    ]
