# Generated by Django 5.2.13 on 2026-04-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_delete_poitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Defective', 'Defective')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderverification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], max_length=20),
        ),
    ]
