# Generated by Django 5.2.13 on 2026-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_purchaseorderitem_status_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Received', 'Received'), ('Verified', 'Verified')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderverification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Received', 'Received'), ('Verified', 'Verified')], max_length=20),
        ),
    ]
