# Generated by Django 5.2.13 on 2026-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_purchaseorder_updated_at_purchaseorderitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Defective', 'Defective'), ('Missing', 'Missing'), ('Few Defective', 'Few Defective')], default='Pending', max_length=20),
        ),
    ]
