# Generated by Django 5.2.13 on 2026-05-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_alter_purchaseorderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('All Defective', 'All Defective'), ('Missing', 'Missing'), ('Defective', 'Defective')], default='Pending', max_length=20),
        ),
    ]
