# Generated by Django 5.2.13 on 2026-05-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_alter_purchaseorderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='defective_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='missing_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
